{% set name = "intake-esgf" %}
{% set version = "2024.1.26" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 15a817bac1701cd4751376d15dbb42c4ebabcd89b7512b5ebe5cccde67be2864

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.9
    - pandas
    - xarray
    - xarray-datatree
    - netCDF4
    - globus-sdk
    - requests
    - tqdm

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/esgf2-us/intake-esgf
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Programmatic access to the ESGF index and data holdings
  dev_url: https://github.com/esgf2-us/intake-esgf
  doc_url: https://intake-esgf.readthedocs.io/en/latest/


extra:
  recipe-maintainers:
    - nocollier
