{% set name = "intake-esgf" %}
{% set version = "2025.5.22" %}
{% set python_min = "3.10" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/intake_esgf-{{ version }}.tar.gz
  sha256: 32a81a043ea4ef751a8bab39dd5df638031fe49108e578287c0b79cf25ab17db

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - dask
    - xarray
    - netCDF4
    - globus-sdk
    - requests
    - pyyaml
    - tqdm  # notebook

test:
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/esgf2-us/intake-esgf
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Programmatic access to the ESGF index and data holdings
  dev_url: https://github.com/esgf2-us/intake-esgf
  doc_url: https://intake-esgf.readthedocs.io/en/latest/


extra:
  recipe-maintainers:
    - nocollier
