{% set name = "intake-esgf" %}
{% set version = "2024.12.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/intake_esgf-{{ version }}.tar.gz
  sha256: a19ca2c51f98721a9ddd7b7e2a405629aa61e97e95a543647f7c94e73f770731

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.9
    - numpy
    - pandas
    - dask
    - xarray
    - netCDF4
    - globus-sdk
    - requests
    - pyyaml
    - tqdm  # notebook

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/esgf2-us/intake-esgf
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Programmatic access to the ESGF index and data holdings
  dev_url: https://github.com/esgf2-us/intake-esgf
  doc_url: https://intake-esgf.readthedocs.io/en/latest/


extra:
  recipe-maintainers:
    - nocollier
