{% set name = "intake-esgf" %}
{% set version = "2025.10.22" %}
{% set python_min = "3.10" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/intake_esgf-{{ version }}.tar.gz
  sha256: dcbb091612b1cd9168ae93b6ce6ab585cf3e1b9eefd47fe9d36954ced856311d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - dask
    - xarray
    - netCDF4
    - globus-sdk
    - requests
    - requests-cache
    - pyyaml
    - tqdm  # notebook
    - pystac-client

test:
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/esgf2-us/intake-esgf
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Programmatic access to the ESGF index and data holdings
  dev_url: https://github.com/esgf2-us/intake-esgf
  doc_url: https://intake-esgf.readthedocs.io/en/latest/


extra:
  recipe-maintainers:
    - nocollier
